---
config:
  layout: cose-bilkent
  look: classic
  theme: default
---
mindmap
  root((Platform))
    Ingress
      CDN
      Load Balancer
    Compute
      API
      Worker
    Data
      Cache
      Primary DB
      Object Store
