// Scaffold flow — runs the seven-step pipeline that produces a fullstack
// project, then writes a `.env` file capturing the chosen variation's
// runtime preset so `make docker-up` / `make ci` pick that combo by default.
//
// The variation is the ONLY user-facing argument. The target is always the
// current working directory. Testing variations is the harness's job
// (tmp/test-matrix.sh + tmp/test-variation.sh); this CLI does not run them.

import { writeFileSync } from "node:fs";
import { join } from "node:path";
import { parseArgs } from "node:util";

import { elog, log } from "../lib/logger.ts";
import { resolveProjectPaths } from "../lib/paths.ts";
import {
  DEFAULT_VARIATION,
  variationByName,
  variationNames,
  type Variation,
} from "../lib/variations.ts";
import { applyResources } from "../steps/05-apply-resources.ts";
import { writeDocs } from "../steps/06-docs.ts";
import { finalize } from "../steps/07-finalize.ts";
import { prepare } from "../steps/01-prepare.ts";
import { scaffoldVite } from "../steps/02-vite-scaffold.ts";
import { installFrontendTooling } from "../steps/03-frontend-tooling.ts";
import { setupTailwindAndShadcn } from "../steps/04-tailwind-shadcn.ts";

export const SCAFFOLD_HELP = `\
setup-fullstack — produce a Python (FastAPI + uv) backend + React (Vite)
                  frontend project with shared Makefile orchestration.

USAGE
  setup-fullstack [variation] [--no-fix] [--no-verify]
  setup-fullstack list-variations
  setup-fullstack --help

ARGUMENTS
  variation           One of the known runtime variations (see list-variations).
                      Writes its env-var bundle to .env in the scaffolded
                      project so \`make docker-up\` / \`make ci\` pick that
                      combo by default. Defaults to "${DEFAULT_VARIATION}".

OPTIONS
  -h, --help          Show this help and exit.
  --no-fix            Skip \`make fix\` autofix pass.
  --no-verify         Skip the typecheck + tests verification step.

EXAMPLES
  setup-fullstack
  setup-fullstack postgres-aws-backup
  setup-fullstack sqlite-persisted --no-verify
  setup-fullstack list-variations
`;

export interface ScaffoldOptions {
  variation: Variation;
  skipFix: boolean;
  skipVerify: boolean;
}

const printSummary = (variation: Variation): void => {
  log("\nSetup complete.\n");
  log(`Variation: ${variation.name}`);
  if (Object.keys(variation.env).length > 0) {
    log("  .env preset written — `make docker-up` / `make ci` honor it by default.");
  }
  log("\nCanonical inner-loop:");
  log("  make fix ci          # autofix everything, then run the strict gate");
  log("\nDev:");
  log("  make dev             # backend 8200 + frontend 5173 (human profile)");
  log("  make agentic-dev     # backend 8201 + frontend 5174 (agent profile)");
  log("\nNarrow inner-loops:");
  log("  make test-py         # backend pytest only");
  log("  make test-ts         # frontend vitest only");
  log("  make test-e2e        # Playwright (auto-launches both halves)");
  log("\nDiscover everything:");
  log("  make help");
};

const writeEnvFile = (projectRoot: string, variation: Variation): void => {
  const envPath = join(projectRoot, ".env");
  if (Object.keys(variation.env).length === 0) {
    log(`  variation '${variation.name}' has no runtime env defaults; skipping .env`);
    return;
  }
  const header = [
    `# Generated by setup-fullstack for variation: ${variation.name}`,
    `# ${variation.description}`,
    "# Edit freely. `make docker-up` and `make ci` read these via the",
    "# `-include .env` directive in the top-level Makefile.",
    "",
  ];
  const lines = Object.entries(variation.env).map(([k, v]) => `${k}=${v}`);
  writeFileSync(envPath, `${header.join("\n")}${lines.join("\n")}\n`);
  log(`  wrote .env (variation: ${variation.name})`);
};

export const runScaffold = async (opts: ScaffoldOptions): Promise<void> => {
  const paths = resolveProjectPaths(".");
  log(`Setting up fullstack app in ${paths.displayName} (variation: ${opts.variation.name})...`);

  const ctx = prepare(paths);
  await scaffoldVite(ctx);
  await installFrontendTooling();
  await setupTailwindAndShadcn(ctx);
  applyResources(ctx);
  writeDocs(ctx);
  writeEnvFile(paths.projectRoot, opts.variation);
  await finalize({ skipFix: opts.skipFix, skipVerify: opts.skipVerify });

  printSummary(opts.variation);
};

/** Parse argv for the scaffold flow. Variation is the first positional. */
export const scaffoldMain = async (argv: string[]): Promise<void> => {
  const { values, positionals } = parseArgs({
    args: argv,
    options: {
      help: { type: "boolean", short: "h", default: false },
      "no-fix": { type: "boolean", default: false },
      "no-verify": { type: "boolean", default: false },
    },
    allowPositionals: true,
    strict: true,
  });

  if (values.help) {
    process.stdout.write(SCAFFOLD_HELP);
    return;
  }

  if (positionals.length > 1) {
    elog(`error: too many positional arguments (got ${positionals.length}, expected 0–1)`);
    elog(`Known variations: ${variationNames().join(", ")}`);
    process.exit(2);
  }

  const variationName = positionals[0] ?? DEFAULT_VARIATION;
  const variation = variationByName(variationName);
  if (!variation) {
    elog(`error: unknown variation '${variationName}'`);
    elog(`Known variations: ${variationNames().join(", ")}`);
    process.exit(2);
  }

  await runScaffold({
    variation,
    skipFix: values["no-fix"] === true,
    skipVerify: values["no-verify"] === true,
  });
};
