#!/usr/bin/env python3
# /// script
# requires-python = ">=3.12"
# dependencies = []
# ///
"""Generate/update the examples README.md from .py + .png pairs.

For each {stem}.py in the examples directory (sorted alphabetically), emits:
  - ## {stem} heading
  - ### Code fence (python, copy-paste-runnable via `uv run`)
  - ### Image (PNG) link

Unlike Mermaid, GitHub cannot live-render a `diagrams` script, so the committed
PNG is the rendered artifact. A static footer documents how to re-render.

Run from project root:
    uv run .claude/skills/mingrammer_diagrams/scripts/_update_examples_readme.py
"""

from __future__ import annotations

import argparse
import logging
import sys
from pathlib import Path
from textwrap import dedent

log = logging.getLogger(__name__)

SCRIPT = Path(__file__)
SCRIPT_NAME = SCRIPT.stem
SCRIPT_DIR = SCRIPT.parent.resolve()

EXAMPLES_DIR = SCRIPT_DIR.parent / "resources" / "examples"
README = EXAMPLES_DIR / "README.md"

HEADER = """\
# Examples

Each example below is a **self-contained, runnable** `diagrams` script. The PNG
is the committed render of that exact source. To reproduce one:

```bash
uv run .claude/skills/mingrammer_diagrams/resources/examples/<name>.py
```

> This file is generated by `scripts/_update_examples_readme.py` (wired to
> `make docs`). Do not edit it by hand — add a `<name>.py` + `<name>.png` pair
> and regenerate.

---

<details>
<summary><b>Table of Contents</b></summary>
<!--TOC-->
<!--TOC-->
</details>

---

"""

FOOTER = """\
## Re-rendering

PNGs are produced by Graphviz via the `diagrams` library. Regenerate every
example PNG (requires `dot` on PATH), then refresh this gallery:

```bash
make -C .claude/skills/mingrammer_diagrams/scripts diagrams   # render *.png
make -C .claude/skills/mingrammer_diagrams/scripts docs       # rebuild this README
```"""


def build_section(stem: str, source: str) -> str:
    """Render one gallery section for a {stem}.py + {stem}.png pair."""
    body = source if source.endswith("\n") else source + "\n"
    return (
        f"## {stem}\n"
        f"\n"
        f"### Code\n"
        f"\n"
        f"```python\n{body}```\n"
        f"\n"
        f"### Image (PNG)\n"
        f"\n"
        f"![{stem}]({stem}.png)\n"
    )


def build_readme(examples_dir: Path = EXAMPLES_DIR) -> str:
    """Build the full README text from every {stem}.py in examples_dir."""
    sources = sorted(examples_dir.glob("*.py"), key=lambda p: p.stem)
    if not sources:
        raise RuntimeError(f"No .py example files found in {examples_dir}")

    missing = [p.stem for p in sources if not (examples_dir / f"{p.stem}.png").exists()]
    if missing:
        raise RuntimeError(
            "Missing rendered PNG(s) for: "
            + ", ".join(missing)
            + " — run `make diagrams` before `make docs`."
        )

    sections = [build_section(src.stem, src.read_text(encoding="utf-8")) for src in sources]
    body = "\n---\n\n".join(sections)
    return HEADER + body + "\n---\n\n" + FOOTER + "\n"


# ============================================================================
# CLI Interface
# ============================================================================


def main(args: argparse.Namespace, readme: Path = README, examples_dir: Path = EXAMPLES_DIR) -> int:
    """Regenerate the examples README from .py + .png pairs."""
    content = build_readme(examples_dir)
    if args.dry_run:
        log.info("DRY RUN: would write %s (%d bytes)", readme, len(content))
        return 0
    readme.write_text(content, encoding="utf-8")
    log.info("Updated %s", readme)
    return 0


if __name__ == "__main__":  # pragma: no cover
    parser = argparse.ArgumentParser(
        formatter_class=argparse.RawDescriptionHelpFormatter,
        description=dedent(f"""\
        {SCRIPT_NAME} — regenerate examples README from .py + .png pairs.

        SOURCE: {EXAMPLES_DIR}
        OUTPUT: {README}
        """),
    )
    parser.add_argument("-v", "--verbose", action="store_true", help="Debug logging")
    parser.add_argument("-q", "--quiet", action="store_true", help="Errors only")
    parser.add_argument(
        "-n",
        "--dry-run",
        action="store_true",
        help="Show what would be written without writing",
    )
    parsed = parser.parse_args()
    logging.basicConfig(
        level=logging.DEBUG if parsed.verbose else logging.ERROR if parsed.quiet else logging.INFO,
        format="%(asctime)s|%(name)s|%(levelname)s|%(filename)s:%(lineno)d - %(message)s",
        datefmt="%Y-%m-%d %H:%M:%S",
    )
    sys.exit(main(parsed))
