---
config:
  layout: tidy-tree
  look: classic
  theme: default
---
mindmap
  root((System))
    Ingress
      CDN
      Load Balancer
    Compute
      API
      Worker
    Data
      Cache
      Primary DB
        Read Replica
      Object Store
